
GET http://localhost:3030/search?cardName=golos

############

GET http://localhost:3030/search?cardName=golos&onStock=false

############

GET http://localhost:3030/cardinfo?cardName=Golos%2C%20Tireless%20Pilgrim

############

GET http://localhost:3030/suggestions?partName=fire

############

GET http://localhost:3030/suggestions?partName=огонь

############

POST http://localhost:3030/bulksearch
content-type: application/json

[
    "Golos, Tireless Pilgrim",
    "Sisay, Weatherlight Captain"
]

############

GET http://localhost:3030/explore?url=https%3A%2F%2Fmtgtrade.net%2Fstore%2Fsingle%2Fuser%2F11077%2F&page=4
